services:
  backupsystem-jellyfin-camera:
    env_file: 
      - ./.env
    image: jellyfin/jellyfin
    container_name: backupsystem-jellyfin-camera
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./jellyconfig:/config
      - ./jellycache:/cache
      - type: bind
        source: ${CAMERA_PATH}
        target: /media/camera
        bind:
          create_host_path: true
    restart: unless-stopped
    ports:
      - ${JELLYFIN_PORT}:8096
      #- ${JELLYFIN_HTTPS_PORT}:8920
      #- ${JELLYFIN_DISCOVERY_PORT}:7359/udp
      #- ${JELLYFIN_DLNA_PORT}:1900/udp